app_about/urls.py
from django.urls import re_path
from .views import viewAbout, saveComment
#url for app

urlpatterns = [
    re_path(r'^about/$', viewAbout, name='view'),
    re_path(r'^about/savelul/$', saveComment, name='data')
]

app_home/urls.py
from django.urls import path, re_path
from .views import index, log_out

urlpatterns = [
    re_path(r'^$', index, name='home'),
    path('news/<int:num>/', index),
    path('logout/', log_out)
]

project_suptix/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    re_path(r'^', include('app_donate.urls')),
    re_path(r'^', include('app_home.urls')),
    re_path(r'^', include(('app_register.urls','register'), namespace='register')),
    re_path(r'^', include('app_program.urls')),
    re_path(r'^', include(('app_about.urls','about'), namespace = 'about')),
    re_path(r'^auth/', include('social_django.urls', namespace='social')),
    path('admin/', admin.site.urls),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_about/models.py
from django.db import models

class Testimoni(models.Model):
	name = models.CharField(max_length = 200)
	testimoni = models.TextField()

	def __str__(self):
		return self.name
# Create your models here.

app_about/forms.py
from django import forms
from .models import Testimoni

class Add_Testimoni_Form(forms.ModelForm):
	class Meta:
		model = Testimoni
		fields = ['testimoni']

	testimoni_attrs = {
		'type': 'text',
        'row' : 4,
        'cols' : 50,
        'class': 'form-control',
        'placeholder':'Text your review here ',
	}
	testimoni = forms.CharField(required=True, label = "Add Testimoni", widget=forms.Textarea(attrs=testimoni_attrs))

app_about/views.py
from django.shortcuts import render
from .models import Testimoni
from .forms import Add_Testimoni_Form
from django.http import HttpResponseRedirect, JsonResponse
from django.db import IntegrityError

response = {}
def viewAbout(request):
	display = Testimoni.objects.all()[::-1]
	response["data"] = display
	response["form"] = Add_Testimoni_Form
	html = "about.html"
	return render(request, html, response)

def saveComment(request):
	data = []		
	form = Add_Testimoni_Form(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		print("meeeoong")
		bucket = {}
		bucket['name'] = request.user.first_name
		bucket['testimoni'] = request.POST['testimoni']
		model = Testimoni(name = bucket['name'] , testimoni = bucket['testimoni'])
		model.save()
		data.append(bucket)
		return JsonResponse({'data' : data}) 
	else:
		return HttpResponseRedirect("/about/")
	

	

app_about/templates/about.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>
		{% block title %}
        	Suptix - About
    	{% endblock title %}
	</title>
</head>
<body>
	{% block content %}
	<div class = "selimut">
	<div>
		<h1> About Suptix </h1>
		<p> Suptix is a website where those who helps and those who needs meets </p>
	</div>
	{% if user.is_authenticated %}
		<div class = "comment-class-custom">
			<div>
					<form class="form" action="{% url 'about:data' %}" method="POST" id = "formtesti">
					{% csrf_token %}
					<div class="form-group">
						{{form}}
					</div>
					<button type="submit" class="btn btn-primary" style = "display:block;">Confirm </button>

					<p style = "margin-top: 20px">
					</p>
				</form>
			</div>
		</div>
		{% else %}
		<div>
			<p>login to write a comment</p>
		</div>
		{% endif %}
		<div style = "max-width: 800px;"><b>What are they say about us?</b></div>
		<div style = "margin-bottom: 30px;">
			<div id = "datajson"></div>
			{% for i in data %}
				<div class = "statusdiv">
					<p class = "statustext">Name : <b>{{i.name}}</b></p>
					<p class = "statustext"><i>" {{i.testimoni}} "</i></p>
				</div>
		
			{% endfor %}
		</div>
	</div>
    {%endblock%}
    {% block script %}
  		<script src="{% static 'about.js'%}"></script>
	{% endblock script %}
</body>