app_home/urls.py
from django.urls import path, re_path
from .views import index, log_out

urlpatterns = [
    re_path(r'^$', index, name='home'),
    path('news/<int:num>/', index),
    path('logout/', log_out)
]

app_register/urls.py
from django.urls import re_path
from .views import registerView, saveRegisterView
#url for app

urlpatterns = [
    re_path(r'^register/$', registerView, name='form'),
    re_path(r'^register/savelul/$', saveRegisterView, name='save')
]

project_suptix/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    re_path(r'^', include('app_donate.urls')),
    re_path(r'^', include('app_home.urls')),
    re_path(r'^', include(('app_register.urls','register'), namespace='register')),
    re_path(r'^', include('app_program.urls')),
    re_path(r'^', include(('app_about.urls','about'), namespace = 'about')),
    re_path(r'^auth/', include('social_django.urls', namespace='social')),
    path('admin/', admin.site.urls),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_register/models.py
from django.db import models
from django.core.exceptions import ValidationError

# Create your models here.
class Register(models.Model):
    nama_donatur = models.CharField(max_length = 50)
    donatur_ttl = models.DateField()
    donatur_email = models.EmailField(max_length = 100, unique=True,)
    donatur_password = models.CharField(max_length = 50)

    def __str__(self):
        return self.donatur_email

app_register/forms.py
from django import forms
from .models import Register

class Add_Register_Form(forms.ModelForm):
    class Meta:
        model = Register
        fields = ['nama','ttl','email','password',]


    nama_donatur_attrs = {
        'type': 'text',
        'class': 'form-control',
        'placeholder':'text your name here',
    }

    donatur_ttl_attrs = {
        'type':'date',
        'class' : 'form-control' 
    }

    donatur_email_attrs = {
        'class' : 'form-control',
        'placeholder': 'fulan123@gmail.com'
    }

    donatur_password_attrs = {
        'type' : 'password', 
        'class' : 'form-control',
        'placeholder':'text your password here',
    }
    
    nama = forms.CharField(required=True, label = 'Full Name', widget=forms.TextInput(attrs = nama_donatur_attrs))
    email = forms.EmailField(required=True, label = 'Email', widget=forms.TextInput(attrs = donatur_email_attrs), error_messages={'unique': 'email already taken!'})
    ttl = forms.DateField(required=True, label = 'Birth Date', widget=forms.DateTimeInput(attrs= donatur_ttl_attrs), input_formats=['%Y-%m-%d'])
    password = forms.CharField(required=True, label = 'Password', widget=forms.TextInput(attrs = donatur_password_attrs))


    

    

app_register/views.py
from django.shortcuts import render
from .models import Register
from .forms import Add_Register_Form
from django.http import HttpResponseRedirect
from django.db import IntegrityError

# Create your views here.
response = {}
def registerView(request):
    html = 'register.html'
    response['register_form'] = Add_Register_Form
    return render(request, html, response)

def saveRegisterView(request):
    form = Add_Register_Form(request.POST or None)
    html = 'registerSave.html'
    try:
        if(request.method == 'POST' and form.is_valid()):
            response['nama'] = request.POST['nama']
            response['ttl'] = request.POST['ttl']
            response['email'] = request.POST['email']
            response['password'] = request.POST['password']
            models = Register(nama_donatur = response['nama'], donatur_ttl = response['ttl'], donatur_email = response['email'], donatur_password = response['password'])
            models.save()
            return render(request, html, response)
        else :
            return HttpResponseRedirect("/register/")
    except IntegrityError:
        return HttpResponseRedirect("/register/")

app_register/templates/register.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>
		{% block title %}
        	Suptix - Register Form
    	{% endblock title %}
	</title>
</head>
<body>
	{% block content %}
			<div class = "form-class-custom">
				<div>
					<h1 style = 'text-align: center'>Registration Form</h1>
					<form class="form" action="{% url 'register:save' %}" method="POST">
						{% csrf_token %}
						<div class="form-group">
							{{ register_form }}
						</div>
						<button type="submit" class="btn btn-primary" style = "display:block;">Confirm </button>
						
						<p style = "margin-top: 20px">
							if you still in this page after clicking submit button, there are 2 reason:
							<ol>
								<li>invalid email input</li>
								<li>your email already exists</li>
							</ol>
						</p>
					</form>
				</div>
			</div>
    {%endblock%}
</body>

app_register/templates/registerSave.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>
		{% block title %}
        	Suptix - Register Form
    	{% endblock title %}
	</title>
</head>
<body>
	<div>
		{% block content %}

		<div style = "margin-bottom : 400px; margin-top : 100px;"" >
			<h2 style = "text-align: center">
				Your data has been recorded. You have taken a step forward to be a good person</h2>
			<a href= "/" class="btn btn-primary" role="button" aria-pressed="true" style="display:block">Home</a>
		</div>
			
		{%endblock%}
	</div>
</body>